# Generated by Django 5.2.7 on 2026-07-15 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_otp_hardening'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='owner_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default=None, help_text='Approval state for station owners. NULL for other roles.', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_username', models.CharField(blank=True, max_length=150)),
                ('action', models.CharField(choices=[('user_activated', 'User activated'), ('user_deactivated', 'User deactivated'), ('user_deleted', 'User deleted'), ('owner_approved', 'Station owner approved'), ('owner_rejected', 'Station owner rejected')], max_length=40)),
                ('target_type', models.CharField(max_length=40)),
                ('target_id', models.CharField(max_length=64)),
                ('target_label', models.CharField(blank=True, max_length=150)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['-created_at'], name='audit_created_idx'), models.Index(fields=['action'], name='audit_action_idx'), models.Index(fields=['target_type', 'target_id'], name='audit_target_idx')],
            },
        ),
    ]
