# Generated by Django 5.2.7 on 2026-07-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_owner_decision_provenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('user_activated', 'User activated'), ('user_deactivated', 'User deactivated'), ('user_deleted', 'User deleted'), ('owner_approved', 'Station owner approved'), ('owner_rejected', 'Station owner rejected'), ('station_activated', 'Station activated'), ('station_deactivated', 'Station deactivated'), ('review_hidden', 'Review hidden'), ('review_restored', 'Review restored'), ('review_deleted', 'Review deleted'), ('admin_promoted', 'Promoted to administrator')], max_length=40),
        ),
    ]
