# Generated by Django 5.2.7 on 2026-07-16 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_admin_promotion_audit_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_e164',
            field=models.CharField(blank=True, default=None, help_text='Canonical identity in E.164 (+CCXXXXXXXXX). NULL for pre-W7 accounts.', max_length=16, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verified_at',
            field=models.DateTimeField(blank=True, default=None, help_text='When this phone was proven. NULL means claimed but unproven.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='token_version',
            field=models.PositiveIntegerField(default=0, help_text='Incremented by logoutEverywhere; asserted in the JWT payload.'),
        ),
        migrations.CreateModel(
            name='AuthIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('phone', 'Phone'), ('google', 'Google'), ('apple', 'Apple'), ('password', 'Password (legacy)')], max_length=20)),
                ('subject', models.CharField(help_text="The provider's opaque ID for this person. Never exposed publicly.", max_length=255)),
                ('verified_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'provider'], name='identity_user_provider_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'subject'), name='unique_identity_per_provider'), models.UniqueConstraint(fields=('user', 'provider'), name='unique_provider_per_user')],
            },
        ),
    ]
