# Generated by Django 5.2.7 on 2026-07-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_backfill_password_identities'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_e164', models.CharField(db_index=True, max_length=16)),
                ('otp_hash', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['phone_e164', '-created_at'], name='phoneverif_lookup_idx')],
            },
        ),
    ]
