# Generated by Django 5.2.7 on 2026-07-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_w7_phone_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, default='', help_text='Human-chosen name. Blank means never set — read display_label instead.', max_length=60),
        ),
    ]
