# Generated by Django 5.2.7 on 2026-07-22 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, help_text='When the user self-deleted. NULL = active account. Set = soft-deleted, restorable on sign-in.', null=True),
        ),
    ]
