# Generated by Django 5.2.2 on 2025-06-14 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_info', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='station_images/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('availability', models.CharField(max_length=100)),
                ('amenities', models.TextField(blank=True)),
                ('charger_type', models.CharField(max_length=50)),
                ('station_count', models.PositiveIntegerField(default=1)),
                ('num_of_charger', models.PositiveIntegerField(default=1)),
                ('power_output_kw', models.FloatField(default=22.0)),
                ('estimated_time_min', models.PositiveIntegerField(default=30)),
                ('price_per_kwh', models.DecimalField(decimal_places=2, max_digits=6)),
                ('charger_brand', models.CharField(blank=True, max_length=50)),
                ('num_of_rate', models.PositiveIntegerField(default=0)),
                ('average_rate', models.FloatField(default=0.0)),
                ('review', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
