# Generated by Django 5.2.7 on 2026-07-22 18:56

from django.db import migrations, models


# Canonical connector codes and the aliases legacy/free-text rows may hold.
_CANONICAL = {'ccs', 'ccs2', 'type1', 'type2', 'chademo', 'gb_t', 'nacs'}
_ALIASES = {
    'ccs1': 'ccs', 'combo': 'ccs', 'combo1': 'ccs',
    'combo2': 'ccs2',
    'j1772': 'type1', 'sae': 'type1',
    'mennekes': 'type2', 'iec62196': 'type2',
    'gbt': 'gb_t',
    'tesla': 'nacs', 'supercharger': 'nacs',
}
# Connectors that are DC by nature; everything else defaults to AC.
_DC_CONNECTORS = {'ccs', 'ccs2', 'chademo', 'gb_t', 'nacs'}


def _normalize(value):
    if not value:
        return value
    key = value.strip().lower().replace(' ', '').replace('/', '_').replace('-', '_')
    key = _ALIASES.get(key, key)
    return key


def normalize_existing(apps, schema_editor):
    """Fold pre-W9 free-text connectors ('CCS', 'Type 2', 'CHAdeMO') onto the
    canonical codes and set charge_mode from the connector (it defaulted to AC
    for every row when the column was added)."""
    Station = apps.get_model('stations', 'Station')
    for station in Station.objects.all().iterator():
        normalized = _normalize(station.charger_type)
        changed = False
        if normalized and normalized != station.charger_type:
            station.charger_type = normalized
            changed = True
        # Backfill mode from the (normalized) connector.
        derived_mode = 'dc' if normalized in _DC_CONNECTORS else 'ac'
        if station.charge_mode != derived_mode:
            station.charge_mode = derived_mode
            changed = True
        if changed:
            station.save(update_fields=['charger_type', 'charge_mode'])


def noop_reverse(apps, schema_editor):
    # Normalisation is not reversible (the original free-text is lost), but the
    # canonical codes remain valid, so reversing the schema needs no data change.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0006_review_moderation'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='charge_mode',
            field=models.CharField(choices=[('ac', 'AC'), ('dc', 'DC')], default='ac', max_length=2),
        ),
        migrations.AlterField(
            model_name='station',
            name='charger_type',
            field=models.CharField(choices=[('ccs', 'CCS'), ('ccs2', 'CCS2'), ('type1', 'Type 1'), ('type2', 'Type 2'), ('chademo', 'CHAdeMO'), ('gb_t', 'GB/T'), ('nacs', 'NACS')], max_length=50),
        ),
        migrations.RunPython(normalize_existing, noop_reverse),
    ]
