# Generated by Django 5.2.7 on 2026-07-22 19:16

import secrets

from django.db import migrations, models


def backfill_charger_codes(apps, schema_editor):
    """Give every existing station an opaque charger code (the QR payload)."""
    Station = apps.get_model('stations', 'Station')
    used = set(
        Station.objects.exclude(charger_code=None).values_list('charger_code', flat=True)
    )
    for station in Station.objects.filter(charger_code=None).iterator():
        code = secrets.token_urlsafe(10)
        while code in used:
            code = secrets.token_urlsafe(10)
        used.add(code)
        station.charger_code = code
        station.save(update_fields=['charger_code'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0007_station_charge_mode_alter_station_charger_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='charger_code',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=32, null=True, unique=True),
        ),
        migrations.RunPython(backfill_charger_codes, noop_reverse),
    ]
