# Generated by Django 5.2.16 on 2026-07-23 10:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0008_station_charger_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='station',
            index=models.Index(fields=['charger_type'], name='station_charger_type_idx'),
        ),
        migrations.AddIndex(
            model_name='station',
            index=models.Index(fields=['charge_mode'], name='station_charge_mode_idx'),
        ),
        migrations.AddIndex(
            model_name='station',
            index=models.Index(fields=['power_output_kw'], name='station_power_idx'),
        ),
        migrations.AddIndex(
            model_name='station',
            index=models.Index(fields=['price_per_kwh'], name='station_price_idx'),
        ),
    ]
