# Generated by Django 5.2.7 on 2026-07-22 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(help_text='Manufacturer / company.', max_length=60)),
                ('model', models.CharField(max_length=60)),
                ('year', models.PositiveIntegerField()),
                ('battery_capacity_kwh', models.DecimalField(decimal_places=2, max_digits=6)),
                ('charger_type', models.CharField(choices=[('ccs', 'CCS'), ('ccs2', 'CCS2'), ('type1', 'Type 1'), ('type2', 'Type 2'), ('chademo', 'CHAdeMO'), ('gb_t', 'GB/T'), ('nacs', 'NACS')], max_length=50)),
                ('plate_number', models.CharField(max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-is_primary', '-created_at', '-id'),
                'indexes': [models.Index(fields=['owner', '-is_primary'], name='vehicle_owner_primary_idx')],
                'constraints': [models.UniqueConstraint(fields=('owner', 'plate_number'), name='unique_plate_per_owner'), models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('owner',), name='unique_primary_vehicle_per_owner'), models.CheckConstraint(condition=models.Q(('battery_capacity_kwh__gt', 0)), name='vehicle_battery_positive')],
            },
        ),
    ]
