# Generated by Django 5.2.7 on 2026-07-22 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_business_integrity'),
        ('stations', '0008_station_charger_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charger_code', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('interrupted', 'Interrupted')], default='active', max_length=12)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('energy_delivered_kwh', models.FloatField(default=0.0)),
                ('price_per_kwh', models.FloatField()),
                ('battery_percent', models.FloatField(blank=True, default=None, null=True)),
                ('end_reason', models.CharField(blank=True, default='', max_length=20)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charging_sessions', to='bookings.booking')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charging_sessions', to='stations.station')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charging_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-started_at', '-id'),
                'indexes': [models.Index(fields=['user', 'status'], name='session_user_status_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user',), name='one_active_session_per_user'), models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('charger_code',), name='one_active_session_per_charger'), models.CheckConstraint(condition=models.Q(('energy_delivered_kwh__gte', 0)), name='session_energy_non_negative')],
            },
        ),
    ]
